services:
  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    image: hackdrop-server
    container_name: hackdrop-server
    restart: unless-stopped
    init: true
    networks:
      - proxy

networks:
  proxy:
    external: true
